package com.myspace.reputation_risk;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Risk implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String riskType;
	private java.lang.String additionalRiskDetails;
	private java.lang.String completedBy;
	private java.lang.Integer riskAmount;

	private java.lang.String region;

	public Risk() {
	}

	public java.lang.String getRiskType() {
		return this.riskType;
	}

	public void setRiskType(java.lang.String riskType) {
		this.riskType = riskType;
	}

	public java.lang.String getAdditionalRiskDetails() {
		return this.additionalRiskDetails;
	}

	public void setAdditionalRiskDetails(java.lang.String additionalRiskDetails) {
		this.additionalRiskDetails = additionalRiskDetails;
	}

	public java.lang.String getCompletedBy() {
		return this.completedBy;
	}

	public void setCompletedBy(java.lang.String completedBy) {
		this.completedBy = completedBy;
	}

	public java.lang.Integer getRiskAmount() {
		return this.riskAmount;
	}

	public void setRiskAmount(java.lang.Integer riskAmount) {
		this.riskAmount = riskAmount;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public Risk(java.lang.String riskType,
			java.lang.String additionalRiskDetails,
			java.lang.String completedBy, java.lang.Integer riskAmount,
			java.lang.String region) {
		this.riskType = riskType;
		this.additionalRiskDetails = additionalRiskDetails;
		this.completedBy = completedBy;
		this.riskAmount = riskAmount;
		this.region = region;
	}

}