package com.myspace.reputation_risk;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Step implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.Integer sequenceNumber;
	private Integer sla;

	public Step() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(java.lang.Integer sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	public java.lang.Integer getSla() {
		return this.sla;
	}

	public void setSla(java.lang.Integer sla) {
		this.sla = sla;
	}

	public Step(java.lang.String name, java.lang.Integer sequenceNumber,
			java.lang.Integer sla) {
		this.name = name;
		this.sequenceNumber = sequenceNumber;
		this.sla = sla;
	}

}